apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://github.com/8gears/n8n-helm-chart.git
      path: charts/n8n
      targetRevision: 1.1.0
      helm:
        releaseName: n8n
        valueFiles:
          - $values/argocd/n8n/values.yaml
    - chart: valkey
      repoURL: https://valkey.io/valkey-helm
      targetRevision: 0.7.7
      helm:
        releaseName: n8n-valkey
        valueFiles:
          - $values/argocd/n8n/valkey-values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/n8n/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
