apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: note-tweet-connector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - chart: note-tweet-connector
      repoURL: https://soli0222.github.io/helm-charts
      targetRevision: 1.0.2
      helm:
        valueFiles:
          - $values/argocd/note-tweet-connector/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/note-tweet-connector/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: note-tweet-connector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
