apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - chart: nfs-subdir-external-provisioner
      repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      targetRevision: 4.0.18
      helm:
        valueFiles:
          - $values/argocd/nfs-subdir-external-provisioner/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy: {}
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
