apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.19.0
      helm:
        valueFiles:
          - $values/argocd/external-dns/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/external-dns/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy: {}
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
