apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - chart: tenant
      repoURL: https://operator.min.io
      targetRevision: 7.1.1
      helm:
        valueFiles:
          - $values/argocd/minio-tenant/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/minio-tenant/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
