apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: traefik-crds
    repoURL: https://traefik.github.io/charts
    targetRevision: 1.11.1
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-crds
  syncPolicy: {}
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
