apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tempo-external
  labels:
    helm.sh/chart: tempo-distributed-1.53.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: gateway
    app.kubernetes.io/version: "2.9.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: conohav2-1.pstr.space
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik-external
  tls:
    - hosts:
        - "tempo.pstr.space"
      secretName: tempo.pstr.space-dns01
  rules:
    - host: "tempo.pstr.space"
      http:
        paths:
          - path: /compactor/ring
            pathType: Prefix
            backend:
              service:
                name: tempo-compactor
                port:
                  number: 3200
          - path: /v1/traces
            pathType: Prefix
            backend:
              service:
                name: tempo-distributor
                port:
                  number: 4318
          - path: /distributor/ring
            pathType: Prefix
            backend:
              service:
                name: tempo-distributor
                port:
                  number: 3200
          - path: /ingester/ring
            pathType: Prefix
            backend:
              service:
                name: tempo-distributor
                port:
                  number: 3200
          - path: /metrics-generator/ring
            pathType: Prefix
            backend:
              service:
                name: tempo-distributor
                port:
                  number: 3200
          - path: /flush
            pathType: Prefix
            backend:
              service:
                name: tempo-ingester
                port:
                  number: 3200
          - path: /shutdown
            pathType: Prefix
            backend:
              service:
                name: tempo-ingester
                port:
                  number: 3200
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tempo-query-frontend
                port:
                  number: 3200