apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-reblend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: spotify-reblend
      repoURL: https://soli0222.github.io/helm-charts
      targetRevision: 0.1.2
      helm:
        valueFiles:
          - $values/argocd/spotify-reblend/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/spotify-reblend/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: spotify-reblend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
