apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-nowplaying
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - chart: spotify-nowplaying
      repoURL: https://soli0222.github.io/helm-charts
      targetRevision: 2.0.1
      helm:
        valueFiles:
          - $values/argocd/spotify-nowplaying/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/spotify-nowplaying/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: spotify-nowplaying
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
