ingress:
  enabled: true
  className: traefik-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: conohav2-1.pstr.space
  hosts:
    - host: spn.soli0222.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - spn.soli0222.com
      secretName: spn.soli0222.com-dns01


config:
  baseUrl: "https://spn.soli0222.com"
  serverUri: "mi.soli0222.com"
  twitterEnabled: "true"
  twitterRequireMisskey: "true"
  twitterAllowedHosts: "mi.soli0222.com"
  existingSecret: "spotify-nowplaying-secret"

monitoring:
  serviceMonitor:
    enabled: true

  prometheusRule:
    enabled: true

postgres:
  enabled: false

externalPostgres:
  host: "spn-cluster-rw"
  port: 5432
  username: "spn"
  database: "spn"

  auth:
    existingSecret: "spn-cluster-app"
    secretKey: "password"
