apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mc-mirror-cronjob
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: mc-mirror-cronjob
      repoURL: https://soli0222.github.io/helm-charts
      targetRevision: 0.2.1
      helm:
        valueFiles:
          - $values/argocd/mc-mirror-cronjob/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mc-mirror-cronjob
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
