apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-external
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 38.0.1
      helm:
        skipCrds: true
        valueFiles:
          - $values/argocd/traefik-external/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/traefik-external/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
