apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimir-external
  labels:
    helm.sh/chart: mimir-distributed-6.0.3
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: conohav2-1.pstr.space
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik-external
  tls:
    - hosts:
        - "mimir.pstr.space"
      secretName: mimir.pstr.space-dns01
  rules:
    - host: "mimir.pstr.space"
      http:
        paths:
          - path: /alertmanager
            pathType: Prefix
            backend:
              service:
                name: mimir-alertmanager
                port:
                  number: 8080
          - path: /multitenant_alertmanager/status
            pathType: Prefix
            backend:
              service:
                name: mimir-alertmanager
                port:
                  number: 8080
          - path: /multitenant_alertmanager/configs
            pathType: Prefix
            backend:
              service:
                name: mimir-alertmanager
                port:
                  number: 8080
          - path: /api/v1/alerts
            pathType: Prefix
            backend:
              service:
                name: mimir-alertmanager
                port:
                  number: 8080
          - path: /api/v1/upload/block/
            pathType: Prefix
            backend:
              service:
                name: mimir-compactor
                port:
                  number: 8080
          - path: /distributor
            pathType: Prefix
            backend:
              service:
                name: mimir-distributor
                port:
                  number: 8080
          - path: /api/v1/push
            pathType: Prefix
            backend:
              service:
                name: mimir-distributor
                port:
                  number: 8080
          - path: /otlp/v1/metrics
            pathType: Prefix
            backend:
              service:
                name: mimir-distributor
                port:
                  number: 8080
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: mimir-query-frontend
                port:
                  number: 8080
          - path: /api/v1/status/buildinfo
            pathType: Prefix
            backend:
              service:
                name: mimir-query-frontend
                port:
                  number: 8080
          - path: /prometheus/config/v1/rules
            pathType: Prefix
            backend:
              service:
                name: mimir-ruler
                port:
                  number: 8080
          - path: /prometheus/api/v1/rules
            pathType: Prefix
            backend:
              service:
                name: mimir-ruler
                port:
                  number: 8080
          - path: /prometheus/api/v1/alerts
            pathType: Prefix
            backend:
              service:
                name: mimir-ruler
                port:
                  number: 8080