apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snmp-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: prometheus-snmp-exporter
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 9.12.0
      helm:
        valueFiles:
          - $values/argocd/ix2215/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/ix2215/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ix2215
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
