persistence:
  data:
    existingClaim: ""
    storageClass: "oky-synology-01"
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  
  music:
    createPv: true
    storageClass: "-"
    size: 500Gi
    accessModes:
      - ReadOnlyMany
    nfs:
      server: "192.168.20.250"
      path: "/volume1/music"
      mountOptions:
        - nfsvers=4.1

ingress:
  enabled: true
  className: traefik-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: conohav2-1.pstr.space
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  hosts:
    - host: navidrome.pstr.space
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - navidrome.pstr.space
      secretName: navidrome.pstr.space-dns01

serviceMonitor:
  enabled: true

config:
  enableInsightsCollector: false
  scanner:
    schedule: "*/5 * * * *"
    purgeMissing: "always"
