apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - chart: mimir-distributed
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.0.3
      helm:
        valueFiles:
          - $values/argocd/mimir/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      path: argocd/mimir/manifests
    - repoURL: https://github.com/grafana/mimir.git
      targetRevision: main
      path: operations/mimir-mixin-compiled
      directory:
        include: '{alerts.yaml,rules.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
