config:
  misskeyHost: "mi.soli0222.com"
  rendererBaseUrl: "http://emoji-service-emoji-renderer:8109"
  existingSecret: "emoji-bot-gateway-secret"

valkey:
  enabled: false

externalValkey:
  host: "emoji-bot-gateway-valkey"

metrics:
  serviceMonitor:
    enabled: true
