apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: note-tweet-connector-secret
  namespace: note-tweet-connector
spec:
  itemPath: vaults/Kubernetes/items/note-tweet-connector-secret
