network:
  global:
    interface: ens3
  private:
    interface: ens7
    address: 192.168.9.7
    subnet: 24

certbot:
  domain: soli0222.com

docker:
  enabled: true

misskey:
  web:
    image: ghcr.io/soli0222/misskey:2025.12.2-psr.9.9
    url: https://mi.soli0222.com

  redis:
    image: redis:7-alpine
    host: redis
    port: 6379

  db:
    image: groonga/pgroonga:4.0.4-alpine-18
    host: db
    port: 5432
    db: misskey
    user: misskey-soli
    dbReplications: false
    dbSlaves: []
      # - host: replica1.example.com
      #   port: 5432
      #   db: misskey
      #   user: misskey-soli
      #   pass: password

  fulltextsearch:
    provider: sqlPgroonga
  
  id: aid
  
  # Number of worker processes
  clusterLimit: 4

  # Job concurrency per worker
  deliverJobConcurrency: 16
  inboxJobConcurrency: 16

  # Job rate limiter
  deliverJobPerSec: 2048
  inboxJobPerSec: 32

  # Job attempts
  deliverJobMaxAttempts: 12
  inboxJobMaxAttempts: 8

  # IP address family used for outgoing request (ipv4, ipv6 or dual)
  outgoingAddressFamily: dual

redis_exporter:
  image: oliver006/redis_exporter:v1.80.1

db_exporter:
  image: quay.io/prometheuscommunity/postgres-exporter:v0.18.1