# Global Ansible Configuration
ansible_port: 22
ansible_user: ubuntu
ansible_ssh_private_key_file: /Users/soli/.ssh/id_ed25519
username: ubuntu

# Software Versions
containerd_version: "2.2.0"
runc_version: "1.3.3"
cni_plugins_version: "1.8.0"
kubernetes_version: 1.34.2

# Network Configuration
pod_network_cidr: 10.26.0.0/16

# Network Addressing Scheme
# .10 = Load Balancer VIP
# .11-.12 = Load Balancers  
# .13-.15 = Control Plane Nodes
# .16-.18 = Worker Nodes

# Derived Variables  
lb_virtual_ip: "192.168.20.10"
controlplane_endpoint: "192.168.20.10:6443"

# Mimir Configuration
mimir_endpoint: "https://mimir.str08.net/api/v1/push"
mimir_org_id: anonymous

# Loki Configuration
loki_endpoint: "https://loki.str08.net/loki/api/v1/push"
loki_org_id: fake
