apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: komga
      repoURL: https://soli0222.github.io/helm-charts
      targetRevision: 1.0.4
      helm:
        valueFiles:
          - $values/argocd/komga/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: komga
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
