env:
  - name: KOMGA_DATABASE_CHECKLOCALFILESYSTEM
    value: "FALSE"
  - name: KOMGA_TASKSDB_CHECKLOCALFILESYSTEM
    value: "FALSE"

persistence:
  config:
    existingClaim: ""
    storageClass: "oky-synology-01"
    size: 1Gi
    accessModes:
      - ReadWriteOnce
  
  data:
    createPv: true
    storageClass: "-"
    size: 10Gi
    accessModes:
      - ReadOnlyMany
    nfs:
      server: "192.168.20.250"
      path: "/volume1/books"
      mountOptions:
        - nfsvers=4.1

ingress:
  enabled: true
  className: traefik-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: conohav2-1.pstr.space
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  hosts:
    - host: komga.pstr.space
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - komga.pstr.space
      secretName: komga.pstr.space-dns01

