applications:
  - name: misskey-polestar
    targets:
      - https://mi.soli0222.com
      - https://summaly.soli0222.com
  - name: spotify-nowplaying
    targets:
      - https://spn.soli0222.com
  - name: navidrome
    targets:
      - https://navidrome.pstr.space
  - name: note-tweet-connector
    targets:
      - https://ntc.pstr.space
  - name: external-services
    targets:
      - https://misskey.io
      - https://x.com
