apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daypassed-bot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - chart: daypassed-bot
      repoURL: https://soli0222.github.io/helm-charts
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/argocd/daypassed-bot/values.yaml
    - repoURL: https://github.com/Soli0222/pke.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: daypassed-bot
  syncPolicy: {}
    # automated:
    #   prune: true
    #   selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
